from OceanDB.OceanDB import OceanDB
from dataclasses import dataclass
from datetime import datetime


@dataclass
class OceanDataField:
    nc_name: str
    nc_scale: int
    nc_offset: int
    python_type: type
    postgres_type: str
    postgres_column_name: str
    postgres_table: str

AlongTrackFields = {

    "latitude": OceanDataField(
        nc_name="latitude",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="double precision",
        postgres_column_name="latitude",
        postgres_table="along_track",
    ),
    "longitude": OceanDataField(
        nc_name="longitude",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="double precision",
        postgres_column_name="longitude",
        postgres_table="along_track",
    ),

    "date_time": OceanDataField(
        nc_name="time",
        nc_scale=1,
        nc_offset=0,
        python_type=datetime,
        postgres_type="timestamp",
        postgres_column_name="date_time",
        postgres_table="along_track",
    ),
    "file_name": OceanDataField(
        nc_name="file_name",
        nc_scale=1,
        nc_offset=0,
        python_type=str,
        postgres_type="text",
        postgres_column_name="file_name",
        postgres_table="along_track",
    ),
    "mission": OceanDataField(
        nc_name="mission",
        nc_scale=1,
        nc_offset=0,
        python_type=str,
        postgres_type="text",
        postgres_column_name="mission",
        postgres_table="along_track",
    ),
    "track": OceanDataField(
        nc_name="track",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="smallint",
        postgres_column_name="track",
        postgres_table="along_track",
    ),
    "cycle": OceanDataField(
        nc_name="cycle",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="smallint",
        postgres_column_name="cycle",
        postgres_table="along_track",
    ),
    "basin_id": OceanDataField(
        nc_name="basin_id",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="smallint",
        postgres_column_name="basin_id",
        postgres_table="along_track",
    ),

    "sla_unfiltered": OceanDataField(
        nc_name="sla_unfiltered",
        nc_scale=1000,   # meters → millimeters
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="sla_unfiltered",
        postgres_table="along_track",
    ),
    "sla_filtered": OceanDataField(
        nc_name="sla_filtered",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="sla_filtered",
        postgres_table="along_track",
    ),
    "dac": OceanDataField(
        nc_name="dac",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="dac",
        postgres_table="along_track",
    ),
    "ocean_tide": OceanDataField(
        nc_name="ocean_tide",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="ocean_tide",
        postgres_table="along_track",
    ),
    "internal_tide": OceanDataField(
        nc_name="internal_tide",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="internal_tide",
        postgres_table="along_track",
    ),
    "lwe": OceanDataField(
        nc_name="lwe",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="lwe",
        postgres_table="along_track",
    ),
    "mdt": OceanDataField(
        nc_name="mdt",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="mdt",
        postgres_table="along_track",
    ),
    "tpa_correction": OceanDataField(
        nc_name="tpa_correction",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="tpa_correction",
        postgres_table="along_track",
    ),
}

EddyFields = {

    "track": OceanDataField(
        nc_name="track",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="integer",
        postgres_column_name="track",
        postgres_table="eddy",
    ),
    "observation_number": OceanDataField(
        nc_name="observation_number",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="smallint",
        postgres_column_name="observation_number",
        postgres_table="eddy",
    ),
    "cyclonic_type": OceanDataField(
        nc_name="cyclonic_type",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="smallint",
        postgres_column_name="cyclonic_type",
        postgres_table="eddy",
    ),
    "date_time": OceanDataField(
        nc_name="time",
        nc_scale=1,
        nc_offset=0,
        python_type=datetime,
        postgres_type="timestamp",
        postgres_column_name="date_time",
        postgres_table="eddy",
    ),

    # -----------------
    # Core location
    # -----------------
    "latitude": OceanDataField(
        nc_name="latitude",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="latitude",
        postgres_table="eddy",
    ),
    "longitude": OceanDataField(
        nc_name="longitude",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="longitude",
        postgres_table="eddy",
    ),
    "latitude_max": OceanDataField(
        nc_name="latitude_max",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="latitude_max",
        postgres_table="eddy",
    ),
    "longitude_max": OceanDataField(
        nc_name="longitude_max",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="longitude_max",
        postgres_table="eddy",
    ),

    # -----------------
    # Amplitude & geometry (scaled)
    # -----------------
    "amplitude": OceanDataField(
        nc_name="amplitude",
        nc_scale=1000,  # meters → mm
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="amplitude",
        postgres_table="eddy",
    ),
    "effective_radius": OceanDataField(
        nc_name="effective_radius",
        nc_scale=1000,  # km → m (typical Copernicus convention)
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="effective_radius",
        postgres_table="eddy",
    ),
    "effective_contour_latitude": OceanDataField(
        nc_name="effective_contour_latitude",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="effective_contour_latitude",
        postgres_table="eddy",
    ),
    "effective_contour_longitude": OceanDataField(
        nc_name="effective_contour_longitude",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="effective_contour_longitude",
        postgres_table="eddy",
    ),
    "effective_contour_shape_error": OceanDataField(
        nc_name="effective_contour_shape_error",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="effective_contour_shape_error",
        postgres_table="eddy",
    ),
    "speed_radius": OceanDataField(
        nc_name="speed_radius",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="speed_radius",
        postgres_table="eddy",
    ),
    "speed_contour_shape_error": OceanDataField(
        nc_name="speed_contour_shape_error",
        nc_scale=1000,
        nc_offset=0,
        python_type=float,
        postgres_type="smallint",
        postgres_column_name="speed_contour_shape_error",
        postgres_table="eddy",
    ),

    "cost_association": OceanDataField(
        nc_name="cost_association",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="cost_association",
        postgres_table="eddy",
    ),
    "effective_area": OceanDataField(
        nc_name="effective_area",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="effective_area",
        postgres_table="eddy",
    ),
    "effective_contour_height": OceanDataField(
        nc_name="effective_contour_height",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="effective_contour_height",
        postgres_table="eddy",
    ),
    "inner_contour_height": OceanDataField(
        nc_name="inner_contour_height",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="inner_contour_height",
        postgres_table="eddy",
    ),
    "speed_area": OceanDataField(
        nc_name="speed_area",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="speed_area",
        postgres_table="eddy",
    ),
    "speed_average": OceanDataField(
        nc_name="speed_average",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="integer",
        postgres_column_name="speed_average",
        postgres_table="eddy",
    ),
    "speed_contour_height": OceanDataField(
        nc_name="speed_contour_height",
        nc_scale=1,
        nc_offset=0,
        python_type=float,
        postgres_type="real",
        postgres_column_name="speed_contour_height",
        postgres_table="eddy",
    ),

    "num_contours": OceanDataField(
        nc_name="num_contours",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="smallint",
        postgres_column_name="num_contours",
        postgres_table="eddy",
    ),
    "num_point_e": OceanDataField(
        nc_name="num_point_e",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="smallint",
        postgres_column_name="num_point_e",
        postgres_table="eddy",
    ),
    "num_point_s": OceanDataField(
        nc_name="num_point_s",
        nc_scale=1,
        nc_offset=0,
        python_type=int,
        postgres_type="smallint",
        postgres_column_name="num_point_s",
        postgres_table="eddy",
    ),
    "observation_flag": OceanDataField(
        nc_name="observation_flag",
        nc_scale=1,
        nc_offset=0,
        python_type=bool,
        postgres_type="boolean",
        postgres_column_name="observation_flag",
        postgres_table="eddy",
    ),
}
